// Generated by CoffeeScript 2.5.1
(function() {
  var Handlebars;

  Handlebars = require('handlebars');

  module.exports = Handlebars.template(function(Handlebars, depth0, helpers, partials, data) {
    var foundHelper, revision, self, versions;
    revision = Handlebars.COMPILER_REVISION;
    versions = Handlebars.REVISION_CHANGES[revision];
    this.compilerInfo = [revision, versions];
    helpers = helpers || Handlebars.helpers;
    foundHelper = void 0;
    self = this;
    return 'A partial.';
  });

}).call(this);
